<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYhiXtzu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYhiXtzu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYhiXtzu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYhiXtzu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYhiXtzu\App_KernelDevDebugContainer([
    'container.build_hash' => 'YhiXtzu',
    'container.build_id' => 'baf0610c',
    'container.build_time' => 1715589520,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYhiXtzu');
