<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPCIxevG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPCIxevG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPCIxevG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPCIxevG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPCIxevG\App_KernelDevDebugContainer([
    'container.build_hash' => 'PCIxevG',
    'container.build_id' => '73f64694',
    'container.build_time' => 1715268349,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPCIxevG');
